; Cooktime: embed MSL source in Metal shaders for runtime compilation
; because Xcode 26 AIR bytecode is incompatible with iOS 16.7 A11 GPU runtime
; just needed for my iphone x tests
[ShaderCompiler]
r.Shaders.ExtraData=1

; Runtime: force text shader compilation from embedded MSL source, same as above
[ConsoleVariables]
r.Shaders.Symbols=1
