[Audio]
UseAudioMixer=True

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX11
!D3D12TargetedShaderFormats=ClearArray
+D3D12TargetedShaderFormats=PCD3D_SM6

[/Script/Engine.RendererSettings]
r.GenerateMeshDistanceFields=True
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
r.DefaultFeature.LocalExposure.HighlightContrastScale=0.8
r.DefaultFeature.LocalExposure.ShadowContrastScale=0.8

[/Script/WorldPartitionEditor.WorldPartitionEditorSettings]
CommandletClass=Class'/Script/UnrealEd.WorldPartitionConvertCommandlet'

[/Script/Engine.UserInterfaceSettings]
bAuthorizeAutomaticWidgetVariableCreation=False
FontDPIPreset=Standard
FontDPI=72

[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/TestMap.TestMap
GameDefaultMap=/Game/TestMap.TestMap
GameInstanceClass=/Game/BP_VoiceGameInstance.BP_VoiceGameInstance_C
ServerDefaultMap=/Game/TestMap.TestMap

[/Script/Engine.NetDriver]
+ChannelDefinitions=(ChannelName=OnsetVoip, ClassName=/Script/OnsetVoip.OnsetVoipDataChannel, StaticChannelIndex=3, bTickOnCreate=true, bServerOpen=true, bClientOpen=true, bInitialServer=true, bInitialClient=true)

[Core.Log]
;LogNet=Verbose
;LogNetTraffic=Verbose
;LogSockets=Verbose
LogOnsetVoip=Verbose
;LogOnsetVoipPacket=VeryVerbose
;LogVoiceDecode=Verbose
;LogVoiceEncode=Verbose
;LogVoiceCapture=Verbose

[ConsoleVariables]
voice.playback.ShouldResync=0
voice.MicNoiseGateThreshold=0.0125
voice.SilenceDetectionThreshold=0.0125

[Voice]
bEnabled=True

