[Audio]
UseAudioMixer=True

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX11
!D3D12TargetedShaderFormats=ClearArray
+D3D12TargetedShaderFormats=PCD3D_SM6

[/Script/Engine.RendererSettings]
r.Mobile.AntiAliasing=1
r.Mobile.ShadingPath=0
r.AllowOcclusionQueries=True
r.TextureStreaming=True
r.VirtualTextures=False
r.PathTracing=False
r.GenerateMeshDistanceFields=False
r.AllowStaticLighting=False
r.Substrate=False
r.Nanite.ProjectEnabled=False
r.DynamicGlobalIlluminationMethod=0
r.ReflectionMethod=0
r.Lumen.HardwareRayTracing=False
r.RayTracing=False
r.PathTracing=False

[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/TestMap.TestMap
GameDefaultMap=/Game/TestMap.TestMap
GameInstanceClass=/Game/BP_VoiceGameInstance.BP_VoiceGameInstance_C
ServerDefaultMap=/Game/TestMap.TestMap

[/Script/Engine.NetDriver]
+ChannelDefinitions=(ChannelName=OnsetVoip, ClassName=/Script/OnsetVoip.OnsetVoipDataChannel, StaticChannelIndex=3, bTickOnCreate=true, bServerOpen=true, bClientOpen=true, bInitialServer=true, bInitialClient=true)

[Core.Log]
;LogNet=Verbose
;LogNetTraffic=Verbose
;LogSockets=Verbose
LogOnsetVoip=Verbose
LogOnsetAudioCapture=Verbose
LogOnsetOpus=Verbose
LogOnsetVoipPacket=Verbose
LogOnsetRNNoise=Verbose
LogOnsetFFmpegConverter=Verbose

[ConsoleVariables]
voice.MicGain=1.0
voice.MicAutoLevel=True
voice.MicSensitivity=0.0

[/Script/IOSRuntimeSettings.IOSRuntimeSettings]
MinimumiOSVersion=IOS_16
AdditionalPlistData=<key>NSMicrophoneUsageDescription</key><string>This app needs access to your microphone to enable voice chat.</string>

[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]
bAndroidVoiceEnabled=True
bRecordPermissionAtStartupEnabled=True
PackageName=com.BlueMountains.[PROJECT]
